### ISSUE TITLE
Uploading to Ansible Galaxy

### ISSUE THREAD

**Issue by ewjoachim** [kwoodson/yedit#20]
Would you consider setting your repo to be a proper Ansible Galaxy role so that we can use it and stay up to date more easily ?

**Comment by kwoodson** [comment]
@ewjoachim 

Thanks for suggesting this.  I'd love to push this upstream.  I need to look into what is involved in that process.

**Comment by fcecagno** [comment]
It would be very helpful if we could add this role to `requirements.yml` like this: http://docs.ansible.com/ansible/latest/galaxy.html#installing-multiple-roles-from-a-file

However, when adding this role to `requirements.yml`, I get `[WARNING]: - yedit was NOT installed successfully: this role does not appear to have a meta/main.yml file.`
It looks like this role isn't following the expected format.

**Comment by kwoodson** [comment]
@fcecagno, added a meta/main.yml

**Comment by fcecagno** [comment]
Perfect, now it was possible to install it using `ansible-galaxy`, thank you.

**Comment by neonardo1** [comment]
Is there some secret to making this work with ansible galaxy?  I use galaxy for other requirements for roles hosted on galaxy itself but not from git.

I'm simply getting this error:

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

I've verified yedit is indeed sitting alongside my other galaxy-installed roles which are functional.

**Comment by kwoodson** [comment]
@neonardo1,

Thanks for trying the module.  I ran a local test of this and ran the following commands:

```
ansible-galaxy install -p roles git+https://github.com/kwoodson/yedit
```

I then wrote a quick test to import this role:
```
---
- hosts: localhost
  tasks:
  - import_role:
      name: roles/yedit

  - yedit:
      content:
        a:
          b: 1
      state: list
      key: a.b
    register: yedout

```
or if the module path is set with `-M`.
```
ansible-playbook -M $(pwd)/roles/yedit testyedit.yml
```

Hope this helps.

**Comment by neonardo1** [comment]
Ah, thanks for making me realize my brain fart.  I forgot to call the role.

```
- name: import yedit role
  import_role:
    name: yedit
```

**Comment by kwoodson** [comment]
@jocelynj, I have tried a few times but the galaxy tool for some reason will not find my role.

**Comment by jocelynj** [comment]
Ok, I will take a look, and propose a pull-request if I can find a solution.

**Comment by kwoodson** [comment]
@jocelynj, I have put it on ansible galaxy but the repository had to take on a rename for the import to happen.

**Comment by jocelynj** [comment]
Thanks @kwoodson - I was finally able to upload my own ansible module to galaxy, with a dependency on yedit.
