### ISSUE TITLE
Licensing the project

### ISSUE THREAD

**Issue by ewjoachim** [kwoodson/yedit#21]
It would be much clearer if your project could advertise its license. Software projects with unknown licences can be hard to use in some cases.

Thank you !

**Comment by luto** [comment]
The code for this repo originated in [openshift-tools](https://github.com/openshift/openshift-tools), which.. does not have a license m)

@kwoodson can you please reply to this? :)

**Comment by kwoodson** [comment]
@luto, @ewjoachim, adding PR #22 .
