### ISSUE TITLE
Preserve comments when editing yaml

### ISSUE THREAD

**Issue by ankurkgupta** [kwoodson/yedit#23]
When editing a yaml all of its comments are removed. It should be possible to preserve it.

**Comment by kwoodson** [comment]
@ankurkgupta 

Thanks for reporting this.  

I have moved this to using ruamel.yaml, specifically the RoundTrip functionality.  I will push out my updates soon.

**Comment by kwoodson** [comment]
@ankurkgupta, please reopen if this doesn't work for you.  I have updated to using ruamel.yaml which supports comments.

**Comment by jeff-cook** [comment]
Comments are still getting removed in the current master branch (https://github.com/kwoodson/ansible-role-yedit/commit/1118b8396380fdd31d16fdd4c874ce000a7773b8)

**Comment by kwoodson** [comment]
@jeff-cook, pyyaml does not preserve comments by default.  ruamel-yaml does allow the preservation of comments.

Do you know which yaml library you are using?

**Comment by jeff-cook** [comment]
Looks like PyYAML 3.13 is the default existing on RHEL. Is a way to get PyYAML to preserve comments with yedit?
